apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: z4d9iz99k-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: z4d9iz99k-go 
  name: z4d9iz99k-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: z4d9iz99k-go 
